name: Build font and specimen

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo snap install yq
    - name: Build font
      run: make build
    - name: Check with fontbakery
      run: make test
      continue-on-error: true
    - name: Generate proofs
      run: make proof
    - name: Create Artifact Folder
      run: New-Item -Path '${{ github.workspace }}' -Name "Artifacts" -ItemType "directory"
      shell: powershell
    - name: Copy Scripts
      run: Copy 'Scripts/' '${{ github.workspace }}/Artifacts/Scripts'
      shell: powershell
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/Artifacts
        name: ${{ github.run_number }}